### ISSUE TITLE
Roadmap.sh

### ISSUE THREAD

**Issue by siddhiiguptaa** [GowthamGoush/Amazing_Sites#10]
Website Link: https://roadmap.sh/
About: It is a community effort to create roadmaps, guides and other educational content to help guide the developers in picking up the path and guide their learnings.

**Comment by GowthamGoush** [comment]
Hey, @siddhiiguptaa, really appreciate your enthusiasm!

**Comment by GowthamGoush** [comment]
Go ahead, @siddhiiguptaa

**Comment by siddhiiguptaa** [comment]
Hey @GowthamGoush Thanks a ton! I am sure this repository will help a lot of people once it has been prepared. All the best!

**Comment by GowthamGoush** [comment]
> Hey @GowthamGoush Thanks a ton! I am sure this repository will help a lot of people once it has been prepared. All the best!

It means a lot, and good luck, @siddhiiguptaa 🙌
