### ISSUE TITLE
Project Euler

### ISSUE THREAD

**Issue by byt3h3ad** [GowthamGoush/Amazing_Sites#100]
Project Euler is a series of challenging mathematical/computer programming problems that will require more than just mathematical insights to solve.

[Project Euler](https://projecteuler.net/archives)

**Comment by Rangaraj-baskar** [comment]
Go ahead @byt3h3ad ! Don't forget to follow the regulations mentioned in README.md !! 
Happy Hacking !!

**Comment by byt3h3ad** [comment]
done!
