### ISSUE TITLE
wttr

### ISSUE THREAD

**Issue by MayankRawat06** [GowthamGoush/Amazing_Sites#105]
click 👇
[wttr](https://wttr.in)
- wttr is a console-oriented weather forecast service that supports various information representation methods like terminal-oriented ANSI-sequences for console HTTP clients (curl, httpie, or wget), HTML for web browsers, or PNG for graphical viewers.
- It uses wego for visualization and various data sources for weather forecast information.

**Comment by GowthamGoush** [comment]
Hey great job, @MayankRawat06 👏
