### ISSUE TITLE
Sangeet

### ISSUE THREAD

**Issue by samikshaupadhyay** [GowthamGoush/Amazing_Sites#115]
Music streaming web page using html css and javascript. 

https://samikshaupadhyay.github.io/sangeet/

**Comment by GowthamGoush** [comment]
Extraordinary to witness your fantastic works, @samikshaupadhyay, but unfortunately, we could not approve this since there are various other platforms for this.

**Comment by GowthamGoush** [comment]
Nevertheless, feel free to add a new site.
