### ISSUE TITLE
hackerrank.com

### ISSUE THREAD

**Issue by anwesha223893** [GowthamGoush/Amazing_Sites#116]
HackerRank is the market-leading technical assessment and remote interview solution for hiring developers. It provides a platform to get knowledge about several skills. It also provides certification for various skills like angular, CSS, Javascript, C, C#, Python at basic and intermediate levels. The best part about this site is that it provides a free interview preparation kit for practicing various coding problems for interview purposes.

**Comment by GowthamGoush** [comment]
Please go ahead, @anwesha223893
