### ISSUE TITLE
Itch.io

### ISSUE THREAD

**Issue by aurora-0025** [GowthamGoush/Amazing_Sites#128]
### DESCRIPTION

itch.io is an open marketplace for independent digital creators with a focus on independent video games. It’s a platform that enables anyone to sell the content they've created. As a seller you’re in charge of how it’s done: you set the price, you run sales, and you design your pages. It’s never necessary to get votes, likes, or follows to get your content approved, and you can make changes to how you distribute your work as frequently as you like.

itch.io is also a collection of some of the most unique, interesting, and independent creations you'll find on the web. We're not your typical digital storefront, with a wide range of both paid and free content, we encourage you to look around and see what you find.

Link:-  [https://itch.io/](https://itch.io/)

**Comment by Rangaraj-baskar** [comment]
Go ahead !! Stick to the regulations !! Happy hacking !!
