### ISSUE TITLE
Code chef

### ISSUE THREAD

**Issue by nayan2306** [GowthamGoush/Amazing_Sites#132]
CodeChef was created as a platform to help programmers make it big in the world of algorithms, computer programming, and programming contests. It hosts three featured contests every month (Long Challenge, CookOff, LunchTime & Starters) and gives away prizes and goodies to the winners as encouragement.
Can I do for this website I will also add image and video .?
Please assign me

**Comment by Rangaraj-baskar** [comment]
Hey @nayan2306  Pls stick to image for now !! Happy Hacking !!

**Comment by nayan2306** [comment]
Okay sure will add in tommorow morning
