### ISSUE TITLE
TinyPNG

### ISSUE THREAD

**Issue by Siddesh-B** [GowthamGoush/Amazing_Sites#164]
TinyPNG uses smart lossy compression techniques to reduce the file size of your WEBP, JPEG and PNG files. By selectively decreasing the number of colors in the image, fewer bytes are required to store the data. The effect is nearly invisible but it makes a very large difference in file size.

LINK : https://tinypng.com/

**Comment by GowthamGoush** [comment]
Go ahead, @Siddesh-B
