### ISSUE TITLE
Improper indentation for Laracasts

### ISSUE THREAD

**Issue by kevinabraham** [GowthamGoush/Amazing_Sites#208]
![image](https://user-images.githubusercontent.com/6373228/136676983-8d2a6d16-685a-4b25-a218-f4eafd54a7da.png)

**Comment by kevinabraham** [comment]
@GowthamGoush , is it ok for me to give this a go?

**Comment by GowthamGoush** [comment]
Yeah, go ahead, @kevinabraham
