### ISSUE TITLE
HowStuffWorks

### ISSUE THREAD

**Issue by adicadi** [GowthamGoush/Amazing_Sites#28]
This website is dedicated entirely to -- you guessed it -- how things work. And by "things," they mean everything: from airbags to regenerative medicine to velocipede carousels. They've covered so much on this website, it'll be hard to run out of things to read about.

https://www.howstuffworks.com/

**Comment by GowthamGoush** [comment]
Interesting site, please go ahead, @adicadi

**Comment by adicadi** [comment]
Sure ✌
