### ISSUE TITLE
dev.to

### ISSUE THREAD

**Issue by DevyaniJain13** [GowthamGoush/Amazing_Sites#40]
**DEV** is a type of Blogging community of software developers for getting together to help one another out. A platform where everyone can share and discover great ideas, having debate and making friends.  It is a blogging platform? A chat room? A forum? All 3 things combined. 

**Link to website** - https://dev.to/

**Comment by GowthamGoush** [comment]
Please go ahead, @DevyaniJain13

**Comment by DevyaniJain13** [comment]
Shorten my description. Please review it and merge my PR.
