### ISSUE TITLE
Sound Of Colleagues

### ISSUE THREAD

**Issue by shinozaki1595** [GowthamGoush/Amazing_Sites#47]
https://soundofcolleagues.com/

- It is a website made to emulate the sounds one would typically hear in a workplace.
- The motivation for it came from the fact that people across the world are stuck at their homes due to the pandemic and are slowly forgetting the workplace ambiance, environment, and sometimes, even chaos.
- The website allows one to fully customize your experience and modify the levels of the different elements as per one's preference.

**Comment by GowthamGoush** [comment]
Please go ahead, @shinozaki1595
