### ISSUE TITLE
A Soft Murmur

### ISSUE THREAD

**Issue by euhidaman** [GowthamGoush/Amazing_Sites#6]
A Soft Murmur is a customizable white-noise machine. Its dashboard, gives you slidable volume bars for five different nature sounds: rain, thunder, waves, wind, and fire.
It is really useful to reduce distractions, and to focus on work.
Or, Users can use it to relax too.

Link: https://asoftmurmur.com

**Comment by GowthamGoush** [comment]
Great to add this website to our list, @euhidaman !
