### ISSUE TITLE
poloksa-ph.com

### ISSUE THREAD

**Issue by throwexceptions** [GowthamGoush/Amazing_Sites#60]
The main purpose of this website is to help Overseas Filipino Workers.

The POLO shall provide maximum services to Filipino Migrant Workers to protect their rights and promote their welfare. In pursuit of this mandate, the POLO shall focus on the following key areas, namely: employment protection and facilitation, provision of welfare services and skills enhancement and other training programs, employment promotion and market development, and linkages with the host government, relevant foreign embassies/consulate, international organizations, the Filipino community and non-governmental institutions in the post.

**NOTE**: I am the author of this website. You may see my digital signature in website's inspect elements below.

**Comment by kailasmanivannan** [comment]
@throwexceptions we are glad to see your enthusiasm, but we are only expecting sites for educational purposes.
