### ISSUE TITLE
https://www.joshwcomeau.com/

### ISSUE THREAD

**Issue by vikkastiwari** [GowthamGoush/Amazing_Sites#69]
It helps you learn all the technologies listed below with amazing animation and live Interaction. Which makes understanding the concept very simple.
For e.g Visit - https://www.joshwcomeau.com/css/designing-shadows/

Technologies 
- React
- Animation
- CSS
- Gatsby
- Next.js

I learned a lot from this website and wanted to share this amazing site with the community.

**Comment by GowthamGoush** [comment]
Please go ahead, @vikkastiwari
